source "https://rubygems.org"

gem "rake"
gem "middleman"
gem "middleman-livereload"
gem "middleman-gh-pages"
gem "middleman-syntax"
gem "middleman-google-analytics"
gem "bootstrap-sass"
gem "redcarpet"
